[Feature]:-Added the blog page and blogs in it
Nactore-Org/Nacto-Care pull request #14
Opened 2024-05-03 12:36 UTC by mohit-bhandari45

Fixes #12

Description:-
So the requirement was to add the blog page where all the blogs will be rendered through the backend. So did I do.
All the blogs will rendered from the database in the form of json. All  the blogs are stored in the react state.
And by react mapping functions all the blogs are shown in the ui.
They are in this form:-
{
            "title": "Lorem Ipsum Blog",
            "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
            "author": "John Doe",
            "publication_date": "2024-05-03"
},

Screenshots:-
![image](https://github.com/Nactore-Org/Nacto-Care/assets/151373021/a7c8d68a-002a-40bf-9ffc-a811c1d872d9)
![image](https://github.com/Nactore-Org/Nacto-Care/assets/151373021/45b9a0f4-fb6c-4c47-9364-cfc5d74e5dc2)

2024-05-03 20:00 UTC, Harshil-Jani commented
@mohit-bhandari45 Great Job. Thanks

Would you like to add another commit where you can just put it in header saying "blog" besides "career" and also add the route link in the footer where it redirects to "/blog" ?

Also please avoid commiting package-lock.json and yarn.lock since the PR doesn't add or remove any dependencies.

2024-05-03 20:01 UTC, Harshil-Jani requested changes

2024-05-03 20:01 UTC, Harshil-Jani commented on package-lock.json
Don't push `package-lock.json`

2024-05-03 20:01 UTC, Harshil-Jani commented on yarn.lock
Don't push `yarn.lock`

2024-05-04 02:58 UTC, mohit-bhandari45 commented
done you can check now

2024-05-04 03:20 UTC, mohit-bhandari45 commented
changes done you can check it out

2024-05-04 13:04 UTC, Harshil-Jani approved these changes
Thanks @mohit-bhandari45

2024-05-04 13:04 UTC, merged